// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASkAtM4zYs8sDR9LPeSPzPsEUMw3rKsVM',
    appId: '1:365998229887:android:8fb1337e1cfc1937f9724a',
    messagingSenderId: '365998229887',
    projectId: 'lakshya-flats',
    storageBucket: 'lakshya-flats.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_Z3zapATrS5wbljalRWNqgNUbGoSbVEo',
    appId: '1:365998229887:ios:4c132b4b74bf0715f9724a',
    messagingSenderId: '365998229887',
    projectId: 'lakshya-flats',
    storageBucket: 'lakshya-flats.firebasestorage.app',
    iosBundleId: 'com.lakshya.residency.lakshyaResidency',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASkAtM4zYs8sDR9LPeSPzPsEUMw3rKsVM',
    appId: '1:365998229887:web:8fb1337e1cfc1937f9724a',
    messagingSenderId: '365998229887',
    projectId: 'lakshya-flats',
    authDomain: 'lakshya-flats.firebaseapp.com',
    storageBucket: 'lakshya-flats.firebasestorage.app',
  );
}
